services:
    becklyn.mysql_dump.configuration:
        class: Becklyn\MysqlDumpBundle\Service\DatabaseConfigurationService
        arguments:
            - @doctrine
            - null
            - null

    becklyn.mysql_dump.dump:
        class: Becklyn\MysqlDumpBundle\Service\MysqlDumpService
        arguments:
            - @service_container
