services:
    becklyn_mysql_dump.services.configuration:
        class: Becklyn\MysqlDumpBundle\Service\DatabaseConfigurationService
        arguments:
            - @doctrine
            - null

    becklyn_mysql_dump.services.dump:
        class: Becklyn\MysqlDumpBundle\Service\MysqlDumpService
        arguments:
            - @service_container
